[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "python3-template"
version = "0.0.1"
description = "This repository is template for my python project."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
authors = [{ name = "Park Sangjun" }]

[project.urls]
Repository = "https://github.com/cosmoquester/python3-template.git"

[dependency-groups]
dev = [
    "ruff",
    "pytest",
    "pytest-cov",
    "codecov",
]

[tool.setuptools.packages.find]
exclude = ["tests*"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.pyright]
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnusedImport = true
reportUnusedVariable = true
reportUnusedClass = true
reportUnusedFunction = true
reportImportCycles = true
reportOptionalMemberAccess = true
reportUntypedBaseClass = true
reportPrivateUsage = true
reportConstantRedefinition = true
reportInvalidStringEscapeSequence = true
reportUnnecessaryIsInstance = true
reportUnnecessaryCast = true
reportAssertAlwaysTrue = true
reportSelfClsParameterName = true
