version: 2.1

orbs:
  python: circleci/python@4.0.0

commands:
  install-packages:
    steps:
      - checkout

      - python/install-packages:
          pkg-manager: uv

jobs:
  run-test:
    executor: &python-executor
      name: python/default
      tag: "3.12.12"
    steps:
      - install-packages

      - run:
          name: Run Tests
          command: |
            source .venv/bin/activate
            pytest --cov-branch --cov --cov-report=xml

      - run:
          name: Upload Coverage to Codecov
          command: |
            source .venv/bin/activate
            codecov -f coverage.xml

  check-linting:
    executor: *python-executor
    steps:
      - install-packages

      - run:
          name: Run Ruff
          command: |
            source .venv/bin/activate
            ruff check sample_package tests

workflows:
  main:
    jobs:
      - run-test
      - check-linting
