version: 2.1

orbs:
  codecov: codecov/codecov@5
  python: circleci/python@4.0.0

commands:
  install-packages:
    steps:
      - checkout

      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: Create Virtual Environment and Install Dependencies
          command: |
            uv venv --allow-existing
            source .venv/bin/activate
            uv pip install -r requirements.txt -r requirements-dev.txt

      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - ".venv"

jobs:
  run-test:
    executor: &python-executor
      name: python/default
      tag: "3.12.12"
    steps:
      - install-packages

      - run:
          name: Run Tests
          command: |
            source .venv/bin/activate
            pytest --cov-branch --cov --cov-report=xml

      - codecov/upload

  check-linting:
    executor: *python-executor
    steps:
      - install-packages

      - run:
          name: Run Ruff
          command: |
            source .venv/bin/activate
            ruff check sample_package tests

workflows:
  main:
    jobs:
      - run-test
      - check-linting
