name: CI

on:
  push:
  pull_request:

jobs:
  run-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12.12"
          enable-cache: true

      - name: Install Dependencies
        run: |
          uv venv --allow-existing
          uv pip install -r requirements.txt -r requirements-dev.txt

      - name: Run Tests
        run: |
          source .venv/bin/activate
          pytest --cov-branch --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: true
          use_pypi: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  check-linting:
    name: Check Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12.12"
          enable-cache: true

      - name: Install Dependencies
        run: |
          uv venv --allow-existing
          uv pip install -r requirements.txt -r requirements-dev.txt

      - name: Run Ruff
        run: |
          source .venv/bin/activate
          ruff check sample_package tests
